
safe:        false
auto:        false
server:      true
server_port: 4000
baseurl:    /
url: http://voxbloom.org

source:      .
destination: ./_site
plugins:     ./_plugins

future: true
lsi: false
pygments: false
markdown: rdiscount
permalink: /:year/:month/:day/:title
paginate: 2

rdiscount:
  extensions: [smart]

redcarpet:
  extensions: []

twitter_id: SunsetSparkNYC
